### ISSUE TITLE
Warning: Python callback failedが頻発します。

### ISSUE THREAD

**Issue by ANagoya** [3dManu/customGraphEditor#1]
こちらのカスタムグラフエディタを愛用しております。

いつ頃からか
// Error: RuntimeError: file C:/Users/ユーザー/Documents/maya/2019/scripts\customGraphEditor\tangentEditor\tanEditorUI.py line 205: Internal C++ object (PySide2.QtWidgets.QCheckBox) already deleted. // 
// Warning: Python callback failed // 
が出るようになりまして、
tangent や weightを弄れる箇所が消えてしまったりします。
![コメント 2020-05-12 151521](https://user-images.githubusercontent.com/29058589/81644858-7f802880-9463-11ea-90db-4ed849490a81.jpg)

曖昧な記憶だとドッキング位置を変えれるようになった頃からだったかもと。。。
こちらもマシン入れ替えなどもした頃なのでもしかしたらMaya側問題かもしれませんが
改善、ご指摘あるとありがたいです。
よろしくお願いします。

**Comment by 3dManu** [comment]
確認が遅くおそくなりました。
Maya2019にて同様のエラーを確認できました。
修正いたしましたら、追って連絡いたします。

**Comment by ANagoya** [comment]
確認、ご対応ありがとうございます！

**Comment by 3dManu** [comment]
maya2019にて発生するエラーを修正いたしました。
workspaceControlの-visibleの挙動が2017と2019で変わっていたのが原因でした。
-visibleの代わりに-raiseを使用することによって、不具合はなくなったと思います。

**Comment by ANagoya** [comment]
ありがとうございます！
やはり使いやすく、非常に快適です！
